### ISSUE TITLE
Arithmetic operation '-1060120681 * 31' (on type 'Int') results in an overflow

### ISSUE THREAD

**Issue by bohdan-ios** [leif-ibsen/SwiftECC#2] opened 2020-11-22 10:13 UTC
Greetings,

**Steps to reproduce**

1. Create a new project with the package.
2. Choose "Any iOS Device" to build.
3. Start building.

**Error**

Arithmetic operation '-1060120681 * 31' (on type 'Int') results in an overflow.
```
    // Small prime product
    static let SPP = BInt(3 * 5 * 7 * 11 * 13 * 17 * 19 * 23 * 29 * 31 * 37 * 41)
```

**Possible solution**

Replace multiplication with initialization from String: 
```
static let SPP = BInt("152125131763605")!
```

**Comment by leif-ibsen** [comment] 2020-11-23 16:22
The issue is fixed in BigInt release 1.2.2

**Closed as completed by leif-ibsen** 2020-11-23 16:22 UTC
